#include "numpy_random_state.h"

#include <algorithm>
#include <cmath>
#include <limits>
#include <new>
#include <numeric>
#include <thread>
#include <type_traits>
#include <unordered_set>

#if defined(__AVX2__)
#include <immintrin.h>
#endif

namespace
{

constexpr std::uint32_t MatrixA = 0x9908b0dfU;
constexpr std::uint32_t UpperMask = 0x80000000U;
constexpr std::uint32_t LowerMask = 0x7fffffffU;

inline std::uint32_t temper_mt(
    std::uint32_t value) noexcept
{
    value ^= value >> 11;
    value ^= (value << 7) & 0x9d2c5680U;
    value ^= (value << 15) & 0xefc60000U;
    value ^= value >> 18;
    return value;
}

inline double random_from_tempered_words(
    std::uint32_t first,
    std::uint32_t second) noexcept
{
    const std::uint32_t a =
        first >> 5;
    const std::uint32_t b =
        second >> 6;
    return
        (static_cast<double>(a) * 67108864.0
         + static_cast<double>(b))
        / 9007199254740992.0;
}

std::uint64_t bit_mask(std::uint64_t value)
{
    value |= value >> 1;
    value |= value >> 2;
    value |= value >> 4;
    value |= value >> 8;
    value |= value >> 16;
    value |= value >> 32;
    return value;
}

double kahan_sum(
    const std::vector<double>& values)
{
    if (values.empty())
    {
        return 0.0;
    }

    double sum = values.front();
    double compensation = 0.0;

    for (std::size_t i = 1; i < values.size(); ++i)
    {
        const double y =
            values[i] - compensation;
        const double next =
            sum + y;

        compensation =
            (next - sum) - y;
        sum = next;
    }

    return sum;
}

bool checked_poisson_candidate(
    double value,
    std::int64_t& result) noexcept
{
    // static_cast<int64_t>(double) is undefined outside the destination
    // range. INT64_MAX rounds to 2^63 as a double, so use that exact value as
    // an exclusive upper bound before performing the conversion. This also
    // rejects NaN/infinity generated by an extreme PTRS proposal.
    constexpr double Int64ExclusiveUpper = 0x1p63;
    if (!(value >= 0.0 && value < Int64ExclusiveUpper))
    {
        return false;
    }
    result = static_cast<std::int64_t>(value);
    return true;
}

// std::vector(size) performs a full zero-fill before a distribution
// immediately overwrites every scalar. NumPy's C kernels allocate an
// uninitialized contiguous output buffer instead. For the pinned GNU C++
// deployment, start the lifetime of trivial scalars without value-initializing
// them, advance libstdc++'s finish pointer, then move the base vector out. This
// saves one complete memory pass while retaining the existing std::vector API.
// The fallback remains fully portable (but pays the zero-fill) on other STLs.
#if defined(__GLIBCXX__)
static_assert(
    _GLIBCXX_RELEASE == 11 &&
        __GLIBCXX__ == 20230528 &&
        __GNUC__ == 11 &&
        __GNUC_MINOR__ == 4,
    "DirectOutputVector is pinned to GCC 11.4/libstdc++ 11 (20230528); "
    "audit the vector layout and rerun Random differential/sanitizer tests "
    "before changing this guard");

template<typename T>
class DirectOutputVector final : public std::vector<T>
{
    static_assert(
        std::is_trivial_v<T> &&
            std::is_trivially_destructible_v<T>,
        "direct output storage is only valid for trivial scalar values");

public:
    explicit DirectOutputVector(
        std::size_t size)
    {
        // Avoid even null + 0 pointer arithmetic on an empty allocation.
        if (size == 0)
        {
            return;
        }
        this->reserve(size);
        T* const begin = this->data();
        for (std::size_t index = 0;
             index < size;
             ++index)
        {
            ::new (static_cast<void*>(begin + index)) T;
        }
        this->_M_impl._M_finish =
            this->_M_impl._M_start + size;
    }

    std::vector<T> release() && noexcept
    {
        auto& base =
            static_cast<std::vector<T>&>(*this);
        return std::move(base);
    }
};

template<typename T>
std::vector<T> direct_output_vector(
    std::size_t size)
{
    return DirectOutputVector<T>(size)
        .release();
}
#else
template<typename T>
std::vector<T> direct_output_vector(
    std::size_t size)
{
    return std::vector<T>(size);
}
#endif

#if defined(__AVX2__)
using CompactIndices =
    std::array<std::array<std::int32_t, 8>, 256>;

constexpr CompactIndices make_compact_indices()
{
    CompactIndices table{};
    for (std::size_t mask = 0;
         mask < table.size();
         ++mask)
    {
        std::size_t output = 0;
        for (std::int32_t lane = 0;
             lane < 8;
             ++lane)
        {
            if ((mask & (std::size_t{1} << lane)) != 0)
            {
                table[mask][output++] = lane;
            }
        }
        while (output < 8)
        {
            table[mask][output++] = 0;
        }
    }
    return table;
}

alignas(32) constexpr CompactIndices
    compact_indices = make_compact_indices();
#endif

template<typename Function>
void parallel_chunks(
    std::size_t size,
    Function function,
    std::size_t parallel_threshold = 262144)
{
    const unsigned available =
        std::thread::hardware_concurrency();
    const std::size_t thread_count =
        size < parallel_threshold || available < 2
        ? 1
        : std::min<std::size_t>(available, 8);

    if (thread_count == 1)
    {
        function(0, size);
        return;
    }

    std::vector<std::thread> workers;
    workers.reserve(thread_count - 1);
    const std::size_t block =
        (size + thread_count - 1) / thread_count;

    try
    {
        for (std::size_t worker = 1;
             worker < thread_count;
             ++worker)
        {
            const std::size_t begin = worker * block;
            const std::size_t end =
                std::min(size, begin + block);
            workers.emplace_back(
                [=, &function]
                {
                    if (begin < end)
                    {
                        function(begin, end);
                    }
                });
        }
        function(0, std::min(size, block));
    }
    catch (...)
    {
        for (std::thread& worker : workers)
        {
            worker.join();
        }
        throw;
    }

    for (std::thread& worker : workers)
    {
        worker.join();
    }
}

} // namespace

NumpyRandomState::NumpyRandomState(
    std::uint32_t seed_value)
{
    seed(seed_value);
}

void
NumpyRandomState::seed(
    std::uint32_t seed_value)
{
    // NumPy RandomState's scalar legacy seeding is the original MT19937
    // init_genrand recurrence, not CPython's init_by_array path.
    for (std::size_t i = 0; i < StateSize; ++i)
    {
        state_[i] = seed_value;
        seed_value =
            1812433253U
            * (seed_value ^ (seed_value >> 30))
            + static_cast<std::uint32_t>(i + 1);
    }

    position_ = StateSize;
    has_gauss_ = false;
    gauss_ = 0.0;
}

void
NumpyRandomState::twist()
{
    std::uint32_t* const state =
        state_.data();
    std::size_t i = 0;

    for (; i < StateSize - StateMiddle; ++i)
    {
        const std::uint32_t y =
            (state[i] & UpperMask)
            | (state[i + 1] & LowerMask);

        state[i] =
            state[i + StateMiddle]
            ^ (y >> 1)
            ^ ((0U - (y & 1U)) & MatrixA);
    }

    for (; i < StateSize - 1; ++i)
    {
        const std::uint32_t y =
            (state[i] & UpperMask)
            | (state[i + 1] & LowerMask);

        state[i] =
            state[i - (StateSize - StateMiddle)]
            ^ (y >> 1)
            ^ ((0U - (y & 1U)) & MatrixA);
    }

    const std::uint32_t y =
        (state[StateSize - 1] & UpperMask)
        | (state[0] & LowerMask);

    state[StateSize - 1] =
        state[StateMiddle - 1]
        ^ (y >> 1)
        ^ ((0U - (y & 1U)) & MatrixA);

    const std::uint32_t* input = state_.data();
    std::uint32_t* output = tempered_.data();
    for (std::size_t index = 0;
         index < StateSize;
         ++index)
    {
        output[index] = temper_mt(input[index]);
    }
    position_ = 0;
}

std::uint32_t
NumpyRandomState::next_uint32()
{
    if (position_ == StateSize)
    {
        twist();
    }

    return tempered_[position_++];
}

std::uint64_t
NumpyRandomState::next_uint64()
{
    return
        (static_cast<std::uint64_t>(
            next_uint32()) << 32)
        | static_cast<std::uint64_t>(
            next_uint32());
}

double
NumpyRandomState::random()
{
    if (position_ + 1 < StateSize)
    {
        const std::uint32_t* const state =
            tempered_.data() + position_;
        position_ += 2;
        return random_from_tempered_words(
            state[0], state[1]);
    }

    // Preserve the exact stream when a double straddles a twist boundary.
    const std::uint32_t first = next_uint32();
    const std::uint32_t second = next_uint32();
    const std::uint32_t a = first >> 5;
    const std::uint32_t b = second >> 6;
    return
        (static_cast<double>(a) * 67108864.0
         + static_cast<double>(b))
        / 9007199254740992.0;
}

void
NumpyRandomState::fill_random(
    double* output,
    std::size_t size)
{
    if (size == 0)
    {
        return;
    }

    double* current = output;
    double* const end = output + size;

    while (current != end)
    {
        if (position_ == StateSize)
        {
            twist();
        }

        const std::size_t available_pairs =
            (StateSize - position_) / 2;
        const std::size_t requested =
            static_cast<std::size_t>(end - current);
        const std::size_t count =
            std::min(available_pairs, requested);

        const std::uint32_t* state =
            tempered_.data() + position_;
        double* const chunk_end = current + count;
        while (current != chunk_end)
        {
            *current++ = random_from_tempered_words(
                state[0], state[1]);
            state += 2;
        }
        position_ += count * 2;

        if (count == 0)
        {
            // Exactly one word remains in this state block.
            *current++ = random();
        }
    }
}

std::vector<double>
NumpyRandomState::random(
    std::size_t size)
{
    std::vector<double> result =
        direct_output_vector<double>(size);
    fill_random(result.data(), result.size());
    return result;
}

NdArray<double>
NumpyRandomState::random(
    const Shape& shape)
{
    const std::size_t size =
        NdArray<double>::checked_size(shape);
    auto values = random(size);
    return NdArray<double>(
        shape,
        std::move(values));
}

double
NumpyRandomState::rand()
{
    return random();
}

NdArray<double>
NumpyRandomState::rand(
    const Shape& dimensions)
{
    return random(dimensions);
}

double
NumpyRandomState::uniform(
    double low,
    double high)
{
    const double range = high - low;

    if (!std::isfinite(range))
    {
        throw std::overflow_error(
            "uniform range exceeds finite double bounds");
    }

    return low + range * random();
}

std::vector<double>
NumpyRandomState::uniform(
    double low,
    double high,
    std::size_t size)
{
    const double range = high - low;
    if (!std::isfinite(range))
    {
        throw std::overflow_error(
            "uniform range exceeds finite double bounds");
    }

    std::vector<double> result =
        direct_output_vector<double>(size);
    for (double& value : result)
    {
        value = low + range * random();
    }
    return result;
}

NdArray<double>
NumpyRandomState::uniform(
    double low,
    double high,
    const Shape& shape)
{
    const std::size_t size =
        NdArray<double>::checked_size(shape);
    auto values = uniform(
        low,
        high,
        size);
    return NdArray<double>(
        shape,
        std::move(values));
}

std::uint64_t
NumpyRandomState::interval(
    std::uint64_t maximum)
{
    if (maximum == 0)
    {
        return 0;
    }

    return interval_masked(
        maximum,
        bit_mask(maximum));
}

std::uint64_t
NumpyRandomState::interval_masked(
    std::uint64_t maximum,
    std::uint64_t mask)
{
    if (maximum == 0)
    {
        return 0;
    }

    std::uint64_t value = 0;
    do
    {
        if (maximum <= 0xffffffffULL)
        {
            value =
                static_cast<std::uint64_t>(
                    next_uint32())
                & mask;
        }
        else
        {
            value = next_uint64() & mask;
        }
    }
    while (value > maximum);

    return value;
}

#if defined(__GNUC__) || defined(__clang__)
__attribute__((hot, flatten))
#endif
void
NumpyRandomState::fill_randint32_fast(
    std::int32_t low,
    std::uint32_t maximum,
    std::uint32_t mask,
    std::int64_t* output,
    std::size_t size)
{
    if (size == 0)
    {
        return;
    }

    std::int64_t* const output_end = output + size;

#if defined(__AVX2__)
    const __m256i vector_mask =
        _mm256_set1_epi32(static_cast<int>(mask));
    const __m256i vector_maximum =
        _mm256_set1_epi32(static_cast<int>(maximum));
    const __m256i vector_low =
        _mm256_set1_epi32(low);
#endif

    while (output != output_end)
    {
        if (position_ == StateSize)
        {
            twist();
        }

        const std::uint32_t* input =
            tempered_.data() + position_;
        const std::uint32_t* const input_end =
            tempered_.data() + StateSize;

#if defined(__AVX2__)
        while (input_end - input >= 8 &&
               output_end - output >= 8)
        {
            const __m256i candidates =
                _mm256_and_si256(
                    _mm256_loadu_si256(
                        reinterpret_cast<const __m256i*>(input)),
                    vector_mask);
            const __m256i rejected =
                _mm256_cmpgt_epi32(
                    candidates, vector_maximum);
            const unsigned accepted_lanes =
                (~static_cast<unsigned>(
                    _mm256_movemask_ps(
                        _mm256_castsi256_ps(rejected)))) & 0xffU;

            __m256i packed = candidates;
            std::size_t accepted_count = 8;
            if (accepted_lanes != 0xffU)
            {
                const __m256i order =
                    _mm256_load_si256(
                        reinterpret_cast<const __m256i*>(
                            compact_indices[accepted_lanes].data()));
                packed = _mm256_permutevar8x32_epi32(
                    candidates, order);
                accepted_count = static_cast<std::size_t>(
                    __builtin_popcount(accepted_lanes));
            }

            packed = _mm256_add_epi32(packed, vector_low);
            const __m128i lower =
                _mm256_castsi256_si128(packed);
            const __m128i upper =
                _mm256_extracti128_si256(packed, 1);
            const __m256i lower64 =
                _mm256_cvtepi32_epi64(lower);
            const __m256i upper64 =
                _mm256_cvtepi32_epi64(upper);
            _mm256_storeu_si256(
                reinterpret_cast<__m256i*>(output),
                lower64);
            _mm256_storeu_si256(
                reinterpret_cast<__m256i*>(output + 4),
                upper64);
            input += 8;
            output += accepted_count;
        }
#endif

        while (input != input_end &&
               output != output_end)
        {
            const std::uint32_t offset =
                *input++ & mask;
            if (offset <= maximum)
            {
                *output++ =
                    static_cast<std::int64_t>(low) + offset;
            }
        }
        position_ = static_cast<std::size_t>(
            input - tempered_.data());
    }
}

void
NumpyRandomState::fill_randint32_pipeline(
    std::int32_t low,
    std::uint32_t maximum,
    std::uint32_t mask,
    std::int64_t* output,
    std::size_t size)
{
#if defined(__AVX2__) && defined(__GLIBCXX__)
    constexpr std::size_t ChunkSize = 1U << 20;
    const __m256i vector_mask =
        _mm256_set1_epi32(static_cast<int>(mask));
    const __m256i vector_maximum =
        _mm256_set1_epi32(static_cast<int>(maximum));
    std::vector<std::thread> workers;
    workers.reserve((size + ChunkSize - 1) / ChunkSize);

    try
    {
        for (std::size_t base = 0; base < size; base += ChunkSize)
        {
            const std::size_t count =
                std::min(ChunkSize, size - base);
            std::int64_t* const destination = output + base;
            std::uint32_t* compact =
                reinterpret_cast<std::uint32_t*>(destination);
            std::uint32_t* const compact_begin = compact;
            std::uint32_t* const compact_end = compact + count;

            while (compact != compact_end)
            {
                if (position_ == StateSize)
                {
                    twist();
                }
                const std::uint32_t* input =
                    tempered_.data() + position_;
                const std::uint32_t* const input_end =
                    tempered_.data() + StateSize;
                while (input_end - input >= 8 &&
                       compact_end - compact >= 8)
                {
                    const __m256i candidates = _mm256_and_si256(
                        _mm256_loadu_si256(
                            reinterpret_cast<const __m256i*>(input)),
                        vector_mask);
                    const __m256i rejected = _mm256_cmpgt_epi32(
                        candidates, vector_maximum);
                    const unsigned accepted_lanes =
                        (~static_cast<unsigned>(_mm256_movemask_ps(
                            _mm256_castsi256_ps(rejected)))) & 0xffU;
                    __m256i packed = candidates;
                    std::size_t accepted_count = 8;
                    if (accepted_lanes != 0xffU)
                    {
                        const __m256i order = _mm256_load_si256(
                            reinterpret_cast<const __m256i*>(
                                compact_indices[accepted_lanes].data()));
                        packed = _mm256_permutevar8x32_epi32(
                            candidates, order);
                        accepted_count = static_cast<std::size_t>(
                            __builtin_popcount(accepted_lanes));
                    }
                    _mm256_storeu_si256(
                        reinterpret_cast<__m256i*>(compact), packed);
                    input += 8;
                    compact += accepted_count;
                }
                while (input != input_end && compact != compact_end)
                {
                    const std::uint32_t offset = *input++ & mask;
                    if (offset <= maximum)
                    {
                        *compact++ = offset;
                    }
                }
                position_ = static_cast<std::size_t>(
                    input - tempered_.data());
            }

            workers.emplace_back(
                [=]
                {
                    const __m256i vector_low = _mm256_set1_epi32(low);
                    std::size_t remaining = count;
                    while (remaining >= 8)
                    {
                        remaining -= 8;
                        __m256i packed = _mm256_loadu_si256(
                            reinterpret_cast<const __m256i*>(
                                compact_begin + remaining));
                        packed = _mm256_add_epi32(packed, vector_low);
                        const __m128i lower =
                            _mm256_castsi256_si128(packed);
                        const __m128i upper =
                            _mm256_extracti128_si256(packed, 1);
                        _mm256_storeu_si256(
                            reinterpret_cast<__m256i*>(
                                destination + remaining),
                            _mm256_cvtepi32_epi64(lower));
                        _mm256_storeu_si256(
                            reinterpret_cast<__m256i*>(
                                destination + remaining + 4),
                            _mm256_cvtepi32_epi64(upper));
                    }
                    while (remaining != 0)
                    {
                        --remaining;
                        destination[remaining] =
                            static_cast<std::int64_t>(low) +
                            compact_begin[remaining];
                    }
                });
        }
    }
    catch (...)
    {
        for (std::thread& worker : workers)
        {
            worker.join();
        }
        throw;
    }
    for (std::thread& worker : workers)
    {
        worker.join();
    }
#else
    fill_randint32_fast(low, maximum, mask, output, size);
#endif
}

std::int64_t
NumpyRandomState::randint(
    std::int64_t high)
{
    return randint(0, high);
}

std::int64_t
NumpyRandomState::randint(
    std::int64_t low,
    std::int64_t high)
{
    if (low >= high)
    {
        throw std::invalid_argument(
            "low must be less than high for randint");
    }

    using Wide = __int128_t;

    const Wide range =
        static_cast<Wide>(high)
        - static_cast<Wide>(low)
        - 1;

    const std::uint64_t offset =
        interval(
            static_cast<std::uint64_t>(range));

    return static_cast<std::int64_t>(
        static_cast<Wide>(low)
        + static_cast<Wide>(offset));
}

std::vector<std::int64_t>
NumpyRandomState::randint(
    std::int64_t low,
    std::int64_t high,
    std::size_t size)
{
    if (low >= high)
    {
        throw std::invalid_argument(
            "low must be less than high for randint");
    }

    using Wide = __int128_t;

    const std::uint64_t maximum =
        static_cast<std::uint64_t>(
            static_cast<Wide>(high)
            - static_cast<Wide>(low)
            - 1);
    const std::uint64_t mask =
        bit_mask(maximum);

    std::vector<std::int64_t> result =
        direct_output_vector<std::int64_t>(size);
    if (result.empty())
    {
        return result;
    }
    std::int64_t* output = result.data();
    std::int64_t* const output_end =
        output + result.size();

    if (maximum == 0)
    {
        std::fill(output, output_end, low);
        return result;
    }

    if (maximum <= 0xffffffffULL)
    {
        const std::uint32_t mask32 =
            static_cast<std::uint32_t>(mask);
        const std::uint32_t maximum32 =
            static_cast<std::uint32_t>(maximum);

        if (maximum32 <= static_cast<std::uint32_t>(
                std::numeric_limits<std::int32_t>::max()) &&
            low >= std::numeric_limits<std::int32_t>::min() &&
            high <= static_cast<std::int64_t>(
                std::numeric_limits<std::int32_t>::max()) + 1)
        {
            if (size >= (1U << 20) &&
                std::thread::hardware_concurrency() >= 2)
            {
                fill_randint32_pipeline(
                    static_cast<std::int32_t>(low),
                    maximum32,
                    mask32,
                    output,
                    size);
            }
            else
            {
                fill_randint32_fast(
                    static_cast<std::int32_t>(low),
                    maximum32,
                    mask32,
                    output,
                    size);
            }
            return result;
        }

#if defined(__AVX2__)
        if (size >= 262144 &&
            maximum32 <= static_cast<std::uint32_t>(
                std::numeric_limits<std::int32_t>::max()) &&
            // The compact two-pass path only pays off when rejection is
            // substantial.  For the common near-power-of-two ranges (and
            // the benchmark's [-1000,1001) range), the direct AVX loop below
            // is faster because it avoids a candidate staging allocation and
            // second memory pass while preserving the same state stream.
            static_cast<std::uint64_t>(maximum32 + 1) * 100ULL <
                static_cast<std::uint64_t>(mask32 + 1) * 85ULL)
        {
            struct CandidateBlock
            {
                std::size_t begin;
                std::size_t end;
                std::size_t output_begin;
            };

            std::vector<std::uint32_t> candidates;
            if (size <=
                (std::numeric_limits<std::size_t>::max() -
                 StateSize) / 2)
            {
                candidates.reserve(size * 2 + StateSize);
            }
            std::vector<CandidateBlock> blocks;
            blocks.reserve(
                size / (StateSize / 2) + 2);

            const __m256i vector_mask =
                _mm256_set1_epi32(
                    static_cast<int>(mask32));
            const __m256i vector_maximum =
                _mm256_set1_epi32(
                    static_cast<int>(maximum32));
            std::size_t accepted_total = 0;

            while (accepted_total < size)
            {
                if (position_ == StateSize)
                {
                    twist();
                }

                const std::uint32_t* const input =
                    tempered_.data() + position_;
                const std::size_t available =
                    StateSize - position_;
                const std::uint32_t* scan = input;
                const std::uint32_t* const scan_end =
                    input + available;
                std::size_t accepted = 0;

                while (scan_end - scan >= 8)
                {
                    const __m256i values =
                        _mm256_and_si256(
                            _mm256_loadu_si256(
                                reinterpret_cast<
                                    const __m256i*>(scan)),
                            vector_mask);
                    const __m256i rejected =
                        _mm256_cmpgt_epi32(
                            values, vector_maximum);
                    const unsigned rejected_lanes =
                        static_cast<unsigned>(
                            _mm256_movemask_ps(
                                _mm256_castsi256_ps(rejected)));
                    accepted +=
                        static_cast<std::size_t>(
                            __builtin_popcount(
                                (~rejected_lanes) & 0xffU));
                    scan += 8;
                }
                while (scan != scan_end)
                {
                    accepted +=
                        ((*scan++ & mask32) <= maximum32)
                        ? 1U
                        : 0U;
                }

                const std::size_t needed =
                    size - accepted_total;
                std::size_t consumed = available;
                if (accepted >= needed)
                {
                    accepted = 0;
                    scan = input;
                    while (accepted < needed)
                    {
                        accepted +=
                            ((*scan++ & mask32) <= maximum32)
                            ? 1U
                            : 0U;
                    }
                    consumed = static_cast<std::size_t>(
                        scan - input);
                }

                const std::size_t candidate_begin =
                    candidates.size();
                candidates.insert(
                    candidates.end(),
                    input,
                    input + consumed);
                blocks.push_back(
                    CandidateBlock{
                        candidate_begin,
                        candidate_begin + consumed,
                        accepted_total});
                position_ += consumed;
                accepted_total += accepted;
            }

            parallel_chunks(
                blocks.size(),
                [&](std::size_t begin, std::size_t end)
                {
                    for (std::size_t block_index = begin;
                         block_index < end;
                         ++block_index)
                    {
                        const CandidateBlock& block =
                            blocks[block_index];
                        std::int64_t* destination =
                            output + block.output_begin;
                        for (std::size_t index = block.begin;
                             index < block.end;
                             ++index)
                        {
                            const std::uint32_t offset =
                                candidates[index] & mask32;
                            if (offset <= maximum32)
                            {
                                *destination++ =
                                    static_cast<std::int64_t>(
                                        static_cast<Wide>(low) +
                                        static_cast<Wide>(offset));
                            }
                        }
                    }
                },
                2);
            return result;
        }
#endif

        while (output != output_end)
        {
            if (position_ == StateSize)
            {
                twist();
            }

            const std::uint32_t* input =
                tempered_.data() + position_;
            const std::uint32_t* const input_end =
                tempered_.data() + StateSize;

#if defined(__AVX2__)
            if (maximum32 <=
                static_cast<std::uint32_t>(
                    std::numeric_limits<std::int32_t>::max()))
            {
                const __m256i vector_mask =
                    _mm256_set1_epi32(
                        static_cast<int>(mask32));
                const __m256i vector_maximum =
                    _mm256_set1_epi32(
                        static_cast<int>(maximum32));
                const __m256i vector_low =
                    _mm256_set1_epi64x(low);
                const bool result_fits_int32 =
                    low >= std::numeric_limits<std::int32_t>::min() &&
                    high <= static_cast<std::int64_t>(
                        std::numeric_limits<std::int32_t>::max()) + 1;
                const __m256i vector_low32 =
                    _mm256_set1_epi32(static_cast<int>(low));

                while (input_end - input >= 8 &&
                       output_end - output >= 8)
                {
                    const __m256i candidates =
                        _mm256_and_si256(
                            _mm256_loadu_si256(
                                reinterpret_cast<
                                    const __m256i*>(input)),
                            vector_mask);
                    const __m256i rejected =
                        _mm256_cmpgt_epi32(
                            candidates,
                            vector_maximum);

                    const unsigned rejected_lanes =
                        static_cast<unsigned>(
                            _mm256_movemask_ps(
                                _mm256_castsi256_ps(rejected)));
                    const unsigned accepted_lanes =
                        (~rejected_lanes) & 0xffU;

                    __m256i packed = candidates;
                    std::size_t accepted_count = 8;
                    if (accepted_lanes != 0xffU)
                    {
                        const __m256i order =
                            _mm256_load_si256(
                                reinterpret_cast<const __m256i*>(
                                    compact_indices[accepted_lanes].data()));
                        packed =
                            _mm256_permutevar8x32_epi32(
                                candidates, order);
                        accepted_count =
                            static_cast<std::size_t>(
                                __builtin_popcount(accepted_lanes));
                    }

                    __m256i lower64;
                    __m256i upper64;
                    if (result_fits_int32)
                    {
                        packed = _mm256_add_epi32(
                            packed, vector_low32);
                        const __m128i lower =
                            _mm256_castsi256_si128(packed);
                        const __m128i upper =
                            _mm256_extracti128_si256(packed, 1);
                        lower64 = _mm256_cvtepi32_epi64(lower);
                        upper64 = _mm256_cvtepi32_epi64(upper);
                    }
                    else
                    {
                        const __m128i lower =
                            _mm256_castsi256_si128(packed);
                        const __m128i upper =
                            _mm256_extracti128_si256(packed, 1);
                        lower64 = _mm256_add_epi64(
                            _mm256_cvtepu32_epi64(lower),
                            vector_low);
                        upper64 = _mm256_add_epi64(
                            _mm256_cvtepu32_epi64(upper),
                            vector_low);
                    }
                    // The loop condition guarantees eight writable live
                    // scalar slots. Packed filler lanes are overwritten by
                    // the next block; only accepted_count advances.
                    _mm256_storeu_si256(
                        reinterpret_cast<__m256i*>(output),
                        lower64);
                    _mm256_storeu_si256(
                        reinterpret_cast<__m256i*>(output + 4),
                        upper64);
                    input += 8;
                    output += accepted_count;
                }
            }
#endif

            while (input != input_end &&
                   output != output_end)
            {
                const std::uint32_t offset =
                    *input++ & mask32;
                if (offset <= maximum32)
                {
                    *output++ =
                        static_cast<std::int64_t>(
                            static_cast<Wide>(low) +
                            static_cast<Wide>(offset));
                }
            }
            position_ = static_cast<std::size_t>(
                input - tempered_.data());
        }
        return result;
    }

    while (output != output_end)
    {
        const std::uint64_t offset =
            interval_masked(maximum, mask);
        *output++ = static_cast<std::int64_t>(
            static_cast<Wide>(low) +
            static_cast<Wide>(offset));
    }
    return result;
}

NdArray<std::int64_t>
NumpyRandomState::randint(
    std::int64_t high,
    const Shape& shape)
{
    return randint(
        0,
        high,
        shape);
}

NdArray<std::int64_t>
NumpyRandomState::randint(
    std::int64_t low,
    std::int64_t high,
    const Shape& shape)
{
    const std::size_t size =
        NdArray<std::int64_t>::checked_size(shape);
    auto values = randint(
        low,
        high,
        size);
    return NdArray<std::int64_t>(
        shape,
        std::move(values));
}

std::vector<std::int64_t>
NumpyRandomState::randints(
    std::int64_t high,
    std::size_t size)
{
    return randint(0, high, size);
}

double
NumpyRandomState::standard_normal()
{
    if (has_gauss_)
    {
        const double result = gauss_;
        has_gauss_ = false;
        gauss_ = 0.0;
        return result;
    }

    double x1 = 0.0;
    double x2 = 0.0;
    double squared_radius = 0.0;

    do
    {
        x1 = 2.0 * random() - 1.0;
        x2 = 2.0 * random() - 1.0;
        squared_radius =
            x1 * x1 + x2 * x2;
    }
    while (squared_radius >= 1.0
           || squared_radius == 0.0);

    const double factor =
        std::sqrt(
            -2.0
            * std::log(squared_radius)
            / squared_radius);

    gauss_ = factor * x1;
    has_gauss_ = true;
    return factor * x2;
}

double
NumpyRandomState::normal(
    double location,
    double scale)
{
    if (scale < 0.0)
    {
        throw std::invalid_argument(
            "normal scale must be non-negative");
    }

    return location + scale * standard_normal();
}

std::vector<double>
NumpyRandomState::normal(
    double location,
    double scale,
    std::size_t size)
{
    if (scale < 0.0)
    {
        throw std::invalid_argument(
            "normal scale must be non-negative");
    }

    std::vector<double> result =
        direct_output_vector<double>(size);
    for (double& value : result)
    {
        value =
            location
            + scale * standard_normal();
    }
    return result;
}

NdArray<double>
NumpyRandomState::normal(
    double location,
    double scale,
    const Shape& shape)
{
    const std::size_t size =
        NdArray<double>::checked_size(shape);
    auto values = normal(
        location,
        scale,
        size);
    return NdArray<double>(
        shape,
        std::move(values));
}

double
NumpyRandomState::exponential(
    double scale)
{
    if (scale < 0.0)
    {
        throw std::invalid_argument(
            "exponential scale must be non-negative");
    }

    return
        scale
        * -std::log(
            1.0 - random());
}

std::vector<double>
NumpyRandomState::exponential(
    double scale,
    std::size_t size)
{
    if (scale < 0.0)
    {
        throw std::invalid_argument(
            "exponential scale must be non-negative");
    }

    std::vector<double> result =
        direct_output_vector<double>(size);
    fill_random(result.data(), result.size());
    double* const output = result.data();
    parallel_chunks(
        result.size(),
        [=](std::size_t begin, std::size_t end)
        {
            for (std::size_t index = begin;
                 index < end;
                 ++index)
            {
                output[index] =
                    scale * -std::log(
                        1.0 - output[index]);
            }
        });
    return result;
}

NdArray<double>
NumpyRandomState::exponential(
    double scale,
    const Shape& shape)
{
    const std::size_t size =
        NdArray<double>::checked_size(shape);
    auto values = exponential(
        scale,
        size);
    return NdArray<double>(
        shape,
        std::move(values));
}

double
NumpyRandomState::log_gamma(
    double value)
{
    static constexpr double coefficients[10] =
    {
        8.333333333333333e-02,
        -2.777777777777778e-03,
        7.936507936507937e-04,
        -5.952380952380952e-04,
        8.417508417508418e-04,
        -1.917526917526918e-03,
        6.410256410256410e-03,
        -2.955065359477124e-02,
        1.796443723688307e-01,
        -1.39243221690590e+00
    };

    std::int64_t n = 0;
    if (value == 1.0 || value == 2.0)
    {
        return 0.0;
    }
    if (value < 7.0)
    {
        n = static_cast<std::int64_t>(
            7.0 - value);
    }

    double x0 =
        value + static_cast<double>(n);
    const double x2 =
        (1.0 / x0) * (1.0 / x0);

    double series = coefficients[9];
    for (int i = 8; i >= 0; --i)
    {
        series *= x2;
        series += coefficients[i];
    }

    double result =
        series / x0
        + 0.5 * 1.8378770664093453e+00
        + (x0 - 0.5) * std::log(x0)
        - x0;

    if (value < 7.0)
    {
        for (std::int64_t i = 1; i <= n; ++i)
        {
            result -= std::log(x0 - 1.0);
            x0 -= 1.0;
        }
    }

    return result;
}

std::int64_t
NumpyRandomState::poisson_unchecked(
    double lambda)
{
    if (lambda == 0.0)
    {
        return 0;
    }

    if (lambda < 10.0)
    {
        const double threshold =
            std::exp(-lambda);

        std::int64_t value = 0;
        double product = 1.0;

        while (true)
        {
            product *= random();
            if (product > threshold)
            {
                ++value;
            }
            else
            {
                return value;
            }
        }
    }

    const double root =
        std::sqrt(lambda);
    const double log_lambda =
        std::log(lambda);
    const double b =
        0.931 + 2.53 * root;
    const double a =
        -0.059 + 0.02483 * b;
    const double inverse_alpha =
        1.1239 + 1.1328 / (b - 3.4);
    const double vr =
        0.9277 - 3.6224 / (b - 2.0);

    while (true)
    {
        const double u =
            random() - 0.5;
        const double v =
            random();
        const double us =
            0.5 - std::fabs(u);

        // The upstream cast after division by us relies on the platform's
        // floating-to-integer behavior when the exact RNG endpoint makes
        // us==0.  That candidate is always rejected, so reject it explicitly
        // after consuming the same two doubles and avoid undefined C++.
        if (us == 0.0)
        {
            continue;
        }

        const double candidate_value =
            std::floor(
                (2.0 * a / us + b) * u
                + lambda
                + 0.43);
        std::int64_t candidate = 0;
        if (!checked_poisson_candidate(
                candidate_value, candidate))
        {
            continue;
        }

        if (us >= 0.07 && v <= vr)
        {
            return candidate;
        }

        if (us < 0.013 && v > us)
        {
            continue;
        }

        if (std::log(v)
                + std::log(inverse_alpha)
                - std::log(a / (us * us) + b)
            <= -lambda
                + static_cast<double>(candidate) * log_lambda
                - log_gamma(
                    static_cast<double>(candidate) + 1.0))
        {
            return candidate;
        }
    }
}

std::int64_t
NumpyRandomState::poisson(
    double lambda)
{
    const double integer_max =
        static_cast<double>(
            std::numeric_limits<std::int64_t>::max());
    const double lambda_max =
        integer_max
        - 10.0 * std::sqrt(integer_max);

    if (!std::isfinite(lambda)
        || lambda < 0.0
        || lambda > lambda_max)
    {
        throw std::invalid_argument(
            "poisson lambda must be finite, non-negative, and representable");
    }

    return poisson_unchecked(lambda);
}

std::vector<std::int64_t>
NumpyRandomState::poisson(
    double lambda,
    std::size_t size)
{
    // Validate before consuming any state, as RandomState does.
    const double integer_max =
        static_cast<double>(
            std::numeric_limits<std::int64_t>::max());
    const double lambda_max =
        integer_max
        - 10.0 * std::sqrt(integer_max);

    if (!std::isfinite(lambda)
        || lambda < 0.0
        || lambda > lambda_max)
    {
        throw std::invalid_argument(
            "poisson lambda must be finite, non-negative, and representable");
    }

    std::vector<std::int64_t> result =
        direct_output_vector<std::int64_t>(size);
    if (result.empty())
    {
        return result;
    }
    std::int64_t* output = result.data();
    std::int64_t* const output_end =
        output + result.size();

    if (lambda == 0.0)
    {
        std::fill(output, output_end, std::int64_t{0});
        return result;
    }

    if (lambda < 10.0)
    {
        const double threshold =
            std::exp(-lambda);
        while (output != output_end)
        {
            std::int64_t value = 0;
            double product = 1.0;
            while (true)
            {
                product *= random();
                if (product > threshold)
                {
                    ++value;
                }
                else
                {
                    *output++ = value;
                    break;
                }
            }
        }
        return result;
    }

    const double root = std::sqrt(lambda);
    const double log_lambda = std::log(lambda);
    const double b = 0.931 + 2.53 * root;
    const double a = -0.059 + 0.02483 * b;
    const double inverse_alpha =
        1.1239 + 1.1328 / (b - 3.4);
    const double log_inverse_alpha =
        std::log(inverse_alpha);
    const double vr =
        0.9277 - 3.6224 / (b - 2.0);

    while (output != output_end)
    {
        while (true)
        {
            const double u = random() - 0.5;
            const double v = random();
            const double us = 0.5 - std::fabs(u);
            if (us == 0.0)
            {
                continue;
            }

            const double candidate_value =
                std::floor(
                    (2.0 * a / us + b) * u +
                    lambda + 0.43);
            std::int64_t candidate = 0;
            if (!checked_poisson_candidate(
                    candidate_value, candidate))
            {
                continue;
            }

            if (us >= 0.07 && v <= vr)
            {
                *output++ = candidate;
                break;
            }
            if (us < 0.013 && v > us)
            {
                continue;
            }

            if (std::log(v) + log_inverse_alpha -
                    std::log(a / (us * us) + b)
                <= -lambda +
                    static_cast<double>(candidate) * log_lambda -
                    log_gamma(
                        static_cast<double>(candidate) + 1.0))
            {
                *output++ = candidate;
                break;
            }
        }
    }
    return result;
}

NdArray<std::int64_t>
NumpyRandomState::poisson(
    double lambda,
    const Shape& shape)
{
    const std::size_t size =
        NdArray<std::int64_t>::checked_size(shape);
    auto values = poisson(
        lambda,
        size);
    return NdArray<std::int64_t>(
        shape,
        std::move(values));
}

std::int64_t
NumpyRandomState::choice(
    std::int64_t population_size)
{
    if (population_size <= 0)
    {
        throw std::invalid_argument(
            "choice population size must be greater than zero");
    }

    return randint(population_size);
}

std::int64_t
NumpyRandomState::choice(
    std::int64_t population_size,
    const std::vector<double>& probabilities)
{
    if (population_size <= 0)
    {
        throw std::invalid_argument(
            "choice population size must be greater than zero");
    }

    const auto indices = choice_indices(
        static_cast<std::size_t>(population_size),
        1,
        &probabilities,
        true);
    return static_cast<std::int64_t>(
        indices.front());
}

std::vector<std::int64_t>
NumpyRandomState::choice(
    std::int64_t population_size,
    std::size_t size,
    bool replace)
{
    // RandomState.choice permits a non-positive integer population only for
    // an empty replacement sample. Handle that before randint validates its
    // bounds; without replacement, a negative population is still invalid.
    if (population_size <= 0)
    {
        if (size == 0 &&
            (population_size == 0 || replace))
        {
            return {};
        }
        throw std::invalid_argument(
            "choice population size must be greater than zero");
    }

    // NumPy returns immediately for a zero-sized result, including the
    // without-replacement path; shuffling the full population here would
    // consume state even though no sample was requested.
    if (size == 0)
    {
        return {};
    }

    if (replace)
    {
        return randint(
            0,
            population_size,
            size);
    }

    const auto indices = choice_indices(
        static_cast<std::size_t>(population_size),
        size,
        nullptr,
        false);
    std::vector<std::int64_t> result;
    result.reserve(indices.size());
    for (std::size_t index : indices)
    {
        result.push_back(
            static_cast<std::int64_t>(index));
    }
    return result;
}

std::vector<std::int64_t>
NumpyRandomState::choice(
    std::int64_t population_size,
    std::size_t size,
    const std::vector<double>& probabilities,
    bool replace)
{
    if (population_size < 0)
    {
        throw std::invalid_argument(
            "choice population size must be non-negative");
    }

    const auto indices = choice_indices(
        static_cast<std::size_t>(population_size),
        size,
        &probabilities,
        replace);
    std::vector<std::int64_t> result;
    result.reserve(indices.size());
    for (std::size_t index : indices)
    {
        result.push_back(
            static_cast<std::int64_t>(index));
    }
    return result;
}

std::vector<std::int64_t>
NumpyRandomState::choice(
    std::int64_t population_size,
    std::size_t size,
    bool replace,
    const std::vector<double>& probabilities)
{
    return choice(
        population_size,
        size,
        probabilities,
        replace);
}

void
NumpyRandomState::validate_probabilities(
    const std::vector<double>& probabilities,
    std::size_t population_size)
{
    if (probabilities.size() != population_size)
    {
        throw std::invalid_argument(
            "population and probabilities must have the same size");
    }

    for (double probability : probabilities)
    {
        if (!std::isfinite(probability))
        {
            throw std::invalid_argument(
                "probabilities must be finite");
        }
        if (probability < 0.0)
        {
            throw std::invalid_argument(
                "probabilities must be non-negative");
        }
    }

    constexpr double tolerance =
        1.4901161193847656e-08;

    if (std::fabs(kahan_sum(probabilities) - 1.0)
        > tolerance)
    {
        throw std::invalid_argument(
            "probabilities do not sum to one");
    }
}

std::vector<std::size_t>
NumpyRandomState::choice_indices(
    std::size_t population_size,
    std::size_t size,
    const std::vector<double>* probabilities,
    bool replace)
{
    if (population_size == 0)
    {
        if (size == 0 && probabilities == nullptr)
        {
            return {};
        }
        throw std::invalid_argument(
            "choice cannot sample an empty population");
    }

    if (probabilities != nullptr)
    {
        validate_probabilities(
            *probabilities,
            population_size);
    }

    // NumPy validates p, then returns an empty result without touching the
    // RNG when no samples are requested. In particular, do not shuffle an
    // entire population for the replace=False,size=0 case.
    if (size == 0)
    {
        return {};
    }

    if (!replace && size > population_size)
    {
        throw std::invalid_argument(
            "cannot sample more items than the population without replacement");
    }

    std::vector<std::size_t> result;
    result.reserve(size);

    if (replace && probabilities == nullptr)
    {
        for (std::size_t i = 0; i < size; ++i)
        {
            result.push_back(
                static_cast<std::size_t>(
                    randint(
                        0,
                        static_cast<std::int64_t>(
                            population_size))));
        }
        return result;
    }

    if (!replace && probabilities == nullptr)
    {
        result.resize(population_size);
        std::iota(
            result.begin(),
            result.end(),
            std::size_t{0});
        shuffle(result);
        result.resize(size);
        return result;
    }

    if (!replace)
    {
        const std::size_t positive =
            static_cast<std::size_t>(
                std::count_if(
                    probabilities->begin(),
                    probabilities->end(),
                    [](double value)
                    {
                        return value > 0.0;
                    }));

        if (positive < size)
        {
            throw std::invalid_argument(
                "fewer non-zero probabilities than requested samples");
        }
    }

    std::vector<double> mutable_probabilities =
        *probabilities;

    do
    {
        if (!replace)
        {
            for (std::size_t index : result)
            {
                mutable_probabilities[index] = 0.0;
            }
        }

        std::vector<double> cumulative(
            population_size);
        std::partial_sum(
            mutable_probabilities.begin(),
            mutable_probabilities.end(),
            cumulative.begin());

        const double total = cumulative.back();
        for (double& value : cumulative)
        {
            value /= total;
        }

        const std::size_t needed =
            replace ? size : size - result.size();

        std::unordered_set<std::size_t> batch_seen;
        for (std::size_t i = 0; i < needed; ++i)
        {
            const double draw = random();
            const std::size_t index =
                static_cast<std::size_t>(
                    std::upper_bound(
                        cumulative.begin(),
                        cumulative.end(),
                        draw)
                    - cumulative.begin());

            if (replace
                || batch_seen.insert(index).second)
            {
                result.push_back(index);
            }
        }
    }
    while (!replace && result.size() < size);

    return result;
}

std::vector<std::int64_t>
NumpyRandomState::permutation(
    std::size_t size)
{
    std::vector<std::int64_t> result(size);
    std::iota(
        result.begin(),
        result.end(),
        std::int64_t{0});
    shuffle(result);
    return result;
}
